### ISSUE TITLE
可否做一个 适配 abp免费版前端的 zorro样板呢？

### ISSUE THREAD

**Issue by DrZhong** [rqx110/abp-ng-zorro#10]
abp企业版太过臃肿，有时候免费版的那个只有用户和角色功能就够开发的了，希望大佬做一个后端基于abp免费版的前端样例

**Comment by rqx110** [comment]
免费版的github上搜一下很多的吧

**Comment by DrZhong** [comment]
目前都是基于ng8 的，还没有基于ng9的...

**Comment by rqx110** [comment]
对着文档自己升级一下，花不了多长时间。
