### ISSUE TITLE
打包出来上千个文件咋搞？

### ISSUE THREAD

**Issue by laosandegudai** [rqx110/abp-ng-zorro#3]
打包出来上千个文件，木有合并打包啊？
![image](https://user-images.githubusercontent.com/17979159/57209330-cd6d7f80-700a-11e9-8bfc-5d8a0b149e3d.png)

**Comment by rqx110** [comment]
主要是因为这里 https://github.com/rqx110/abp-ng-zorro/blob/e938df12e02c0db4988b1a8ad6adb2f918c44dba/angular/src/root.module.ts#L65-L69
和这里 
https://github.com/rqx110/abp-ng-zorro/blob/e938df12e02c0db4988b1a8ad6adb2f918c44dba/angular/src/root.module.ts#L76-L80
采用了动态加载语言，所以ng在打包的时候会把所有语言都打包。

你可以修改成固定import 你所需的语言，然后注册。

**Comment by laosandegudai** [comment]
moment搞得鬼是吧，那就先这样吧。

**Comment by laosandegudai** [comment]
看了你的博客了。

**Comment by rqx110** [comment]
你可以按以下修改只打包部分语言（注意`/* webpackInclude: /(en_US|zh_CN)\.js$/ */`）
```ts
function registerNgZorroLocales(injector: Injector) {
    if (shouldLoadLocale()) {
        let ngZorroLcale = convertAbpLocaleToNgZorroLocale(abp.localization.currentLanguage.name);
        import(
            /* webpackInclude: /(en_US|zh_CN)\.js$/ */
            `ng-zorro-antd/esm5/i18n/languages/${ngZorroLcale}.js`
        ).then(module => {
            let nzI18nService = injector.get(NzI18nService);
            nzI18nService.setLocale(module.default);
        });
    }
}

function registerLocales(resolve: (value?: boolean | Promise<boolean>) => void, reject: any) {
    if (shouldLoadLocale()) {
        let angularLocale = convertAbpLocaleToAngularLocale(abp.localization.currentLanguage.name);
        import(
            /* webpackInclude: /(en|zh)\.js$/ */
            `@angular/common/locales/${angularLocale}.js`
        ).then(module => {
            registerLocaleData(module.default);
            resolve(true);
        }, reject);
    } else {
        resolve(true);
    }
}
```

**Comment by laosandegudai** [comment]
> 你可以按以下修改只打包部分语言（注意`/* webpackInclude: /(en_US|zh_CN)\.js$/ */`）
> 
> ```ts
> function registerNgZorroLocales(injector: Injector) {
>     if (shouldLoadLocale()) {
>         let ngZorroLcale = convertAbpLocaleToNgZorroLocale(abp.localization.currentLanguage.name);
>         import(
>             /* webpackInclude: /(en_US|zh_CN)\.js$/ */
>             `ng-zorro-antd/esm5/i18n/languages/${ngZorroLcale}.js`
>         ).then(module => {
>             let nzI18nService = injector.get(NzI18nService);
>             nzI18nService.setLocale(module.default);
>         });
>     }
> }
> 
> function registerLocales(resolve: (value?: boolean | Promise<boolean>) => void, reject: any) {
>     if (shouldLoadLocale()) {
>         let angularLocale = convertAbpLocaleToAngularLocale(abp.localization.currentLanguage.name);
>         import(
>             /* webpackInclude: /(en|zh)\.js$/ */
>             `@angular/common/locales/${angularLocale}.js`
>         ).then(module => {
>             registerLocaleData(module.default);
>             resolve(true);
>         }, reject);
>     } else {
>         resolve(true);
>     }
> }
> ```

多谢了。
