### ISSUE TITLE
不知道算不算是BUG

### ISSUE THREAD

**Issue by neekin** [rqx110/abp-ng-zorro#6]
abp-ng-zorro/aspnet-core/AspNetZeroRadTool/FileTemplates/Client/Angular/ViewEntityComponentTemplate/MainTemplate.custom.txt

`import { Get{{Entity_Name_Here}}ForViewDto {{Enum_Import_Here}}Dto{{Enum_Import_After_V060600_Here}}{{Enum_Import_Before_V060600_Here}}} from '@shared/service-proxies/service-proxies';`

正确的是不是
`import { Get{{Entity_Name_Here}}ForViewDto {{Entity_Name_Here}}Dto{{Enum_Import_After_V060600_Here}}{{Enum_Import_Before_V060600_Here}}} from '@shared/service-proxies/service-proxies';`

我第一次使用

**Comment by rqx110** [comment]
Thanks!
