### ISSUE TITLE
可以把菜单实现多个tab那样的效果吗

### ISSUE THREAD

**Issue by liwenhai0745** [rqx110/abp-ng-zorro#7]
你好，你提供的模板很好用，但是可以实现多页签菜单吗。就是可以同时打开多个菜单项，tab切换的那种效果

**Comment by rqx110** [comment]
add `<reuse-tab></reuse-tab>` before
https://github.com/rqx110/abp-ng-zorro/blob/d762b5b5459809bb8a369c37d94ff911862134ae/angular/src/app/app.component.html#L5
and alose uncomment below lines
https://github.com/rqx110/abp-ng-zorro/blob/d762b5b5459809bb8a369c37d94ff911862134ae/angular/src/delon.module.ts#L32-L34
